name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Install GpsUtil Module
      run: mvn install:install-file -Dfile=./TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar

    - name: Install RewardCentral Module
      run: mvn install:install-file -Dfile=./TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

    - name: Install RewardCentral Module
      run: mvn install:install-file -Dfile=./TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

    - name: Tests
      run: mvn test -Dtest=!TestPerformance
      working-directory: TourGuide

    - name: Build with Maven
      run: mvn package -DskipTests
      working-directory: TourGuide

    - name: copy the JAR    
      run: mkdir staging && cp TourGuide/target/*.jar staging
    
    - uses: actions/upload-artifact@v3
      with: 
        name: Package
        path: staging

